# Generated by Django 4.1.7 on 2023-02-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='url',
            new_name='slug',
        ),
    ]
